#!/bin/bash
dst=$1
for file in `find . | grep -v "\.git"`; do
    if [ "$file" == "diff" ]; then
        continue
    fi
    echo "COMPARING file $file to $dst/$file"
    diff "$file" "$dst/$file"
    echo -n
done
